apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tomcat
spec:
  type: {{ .Values.service.type }}
  selector:
    app: tomcat
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
